# Generated by Django 4.2.6 on 2023-10-26 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Длинный URL')),
                ('path', models.CharField(blank=True, max_length=10, unique=True, verbose_name='Желаемое сокращение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('num_views', models.IntegerField(default=0, verbose_name='Переходы')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_links', to='sessions.session')),
            ],
        ),
    ]
