name: hemli

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: hemli
      MYSQL_ROOT_PASSWORD: iamroot
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    volumes:
      - redis_data:/data

  web:
    build: .
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - .:/hemli
    depends_on:
      - mysql
      - redis

volumes:
  mysql_data:
  redis_data:

