name: hemli

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: iamroot
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:

